services:
  pgdatabase:
    image: postgres:16
    restart: always
    volumes:
      - "./data/kassal_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    env_file: .env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file: .env